server:
  port: 7000
spring:
  application:
    name: atguigu-crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.150.137
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ali:
  pay:
    app_id: 2021000121665150
    merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDWxMJPCp6gSKPLfBe3xBhuAcHX9BcBmuZWtzdZPPpzAaffkIhghMzW8RGtTT9pIHblGGV7dkoheO2vhducXEXAHZ+LJ1f1/2SuRhn4sNN4kLzyfU9AK5OyMc8B5pTB/UW5VYgX9LL2+ywt0zVuYiU5SNR2I1WTzjTukHgmxyGDMBseN/AIEezsh4e/ERNExpjSsjHSoK4aY267lUeFIyEw5Yes2kjKbGkVRSfBf0K6NpmwlDd9umVyrOZROj/Q0uvOipolHq/rI/HMsUWWZyBdgkTEmGvEaO/QfQF4uQuPfZQU5Eyu3q3mzJ0w4qj8JJterBOiLBv+hBtQX8SLriqjAgMBAAECggEBALkVwhraHRAm6bmwTMRa427SZtqUCcuhUYZDyRhHu9KnB6Rca5s6d0l5YXGHk/EmQDB5EOQQchxcmgHdCwC6aIYDQX5rvptKqNqjoTg4M1bA7YTQxx6XL2avFCYgL+zqN09cTbfPcvf0SAOJ9I8XV9sBT9Ar7VE+sVEzAcjxbYketHUxBOHqZkAm8/SlpheIhq9rie10oPuOKHYg1COOluyUm++2nDDjvvtV+gTn+h8SLGp7MCYA0WEQokQw0DppAUmsCidpIsKENM1xTW2UAwbrZfePK0joB2YbeDdkHzEcht9ZosdzWhILbL2oqBDnG62bx/+UcQ47ac2Q4Km5dlECgYEA9eB8AtHvdF613NmD3ddzxQp8HMuGzGsZO8AOqbJ2IWLOqjRy95+VRXDsTs873+pJDuPMCWAN4HUifmRCGHsPPRDaQ6xP+eN/mdHLCuOaUufJJ1g7zj2fora1Ef/Nu5OTOXVDouy3Yr1XmSDPjNcn+yJuYMMQhGmZMiPiyKEqEzsCgYEA35xlgIg/PAI+c2xdG/wCQh7t1syEvKy7l7OQZZInlTI2nAkQv42uCHtfPKSHNUEWwo2d2xlzGkKrDHUZKuowk5eBFMFg6BljMb+qhEJty5oOEjEJqMox0X/At82Ih5JOR/MVynvbHGDqnLRHBzuYTU10Nvu3RugKN74zdpp0f7kCgYEA3BOGbG/ESQDM/1SiN1q1gNSVqqBxk175QwXxGetm2RM7sBUqIoJwdatRmGjdStrFcdJruqiDQzkVGtRaZNchGKOQ+amuHBmJCQFDIAgBBdv5rIHJZhy6WkX3ZJj2aML6sB9J3vbKXlLjqWg43fNnEd4LtghjLGHogXylbLb0likCgYB3fa6r4aLQ4W4X5edXhfJ6/OYhq4afADr6lOTrsg9e5cdS2HFPu1kthSfeUxlBdve/nUemhlIAzXF0Jbr+OMkehY5f1fp/7NkaA48OQCVF8JvmUrgTr4Cxr+//CGEV+TPFtPuHCWqMHqogdSGjltALNwGMRDSrOmIDaas8jMsGWQKBgQD0mRAMK49htxCTL+yogwtqZOK3oW6Flvdwx9XiiT2JdjFrgkqRZINzg0jHqK8yj/FSmqgKne0ChOKmuHxGzqLLKOikcjO2eYn+UhUmnHa2iq3D+KKcPnWRhco34M5fbnJXGCkySptdyDYpxDdT80VzUKja3yqQyI7koYVqDJpwjw==
    alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjovGYqCxj2/CqR8e8f1fSrmr0t0/asC9d3UQuVUbHX++sII7j7oVzhkaUl0UCvsNezt3PmlmxFFindxeTb8vedIGt945MGk9HQFOarvbQVy7rqqtMCeCfPzE/N0sIn/sHODVlDmBzxlAIuU3+IjCH4sl/VEMj6s06VrGFUhyYsKSXXobuzYNJfAqAnz6CGPPzC1sqR2fqU+v0qeAPH8JbeH913uw/70Ke69NQU6UuVqqiGp+e7GK9Z5kAJp3aWEQA6g8QvJNej7E+j6PHr78LTI23lam+QsHThpTKSEBMID/PeTlhFxfDOoIGDu+0tyhC2tKdAxQ8LH3tVBMmQzpEQIDAQAB
    notify_url: http://5dc91909.r3.cpolar.top/pay/notify
    return_url: http://localhost:81/pay/return
    sign_type: RSA2
    charset: utf-8
    # gatewayUrl: https://openapi.alipay.com/gateway.do # 正式环境的网关
    gatewayUrl: https://openapi.alipaydev.com/gateway.do # 沙箱网关
    log_path: D:\\PracticalExercise\\23.CloudNative\\alipay.trade-page.pay-JAVA-UTF-8
